ls synthetic/bed1* > bed1.list
ls synthetic/bed2* > bed2.list
ls synthetic/bed4* > bed4.list
ls synthetic/chair1* > chair1.list
ls synthetic/chair2* > chair2.list
ls synthetic/chair3* > chair3.list
ls synthetic/chair4* > chair4.list
ls synthetic/monitortelevision1* > monitortelevision1.list
ls synthetic/sofa1* > sofa1.list
ls synthetic/sofa2* > sofa2.list
ls synthetic/sofa3* > sofa3.list
ls synthetic/sofa4* > sofa4.list
ls synthetic/table1* > table1.list
ls synthetic/table2* > table2.list
ls synthetic/table3* > table3.list
ls synthetic/table4* > table4.list
